### ISSUE TITLE
Make a dummy frontend

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/devdao-domains#1]
Just a static UI to get the UI/design out of the way so that we can easily integrate the API/contract later on

**Comment by Dhaiwat10** [comment]
Thinking of using Chakra to get started quickly without needing a designer

**Comment by PBillingsby** [comment]
If you need help on this let me know

**Comment by Dhaiwat10** [comment]
@PBillingsby sorry I forgot to merge the PR and close this, but we need some help on #6
