### ISSUE TITLE
Add a dummy NFTs section to the profile page

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/devdao-domains#3]
We want users to be able to display their NFTs on their profiles. Let's add a section to the bottom of the current profile page containing a grid of cards showing NFTs. You can use this as a reference: https://web3-ui.vercel.app/?path=/docs/components-nft--image

These NFTs don't need to come from an API for now. Just use some dummy data like the other sections.

**Comment by Nazeeh21** [comment]
I would like to work on this
